# Generated by Django 5.1.4 on 2024-12-18 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.TimeField(default=django.utils.timezone.now)),
                ('is_nice', models.BooleanField(default=False)),
                ('periodicity', models.CharField(choices=[('every_hour', 'каждый час'), ('twice_day', 'дважды в день'), ('three_times_day', 'трижды в день'), ('every_day', 'каждый день'), ('every_two_days', 'каждые два дня'), ('every_three_days', 'каждые три дня'), ('every_five_days', 'каждые пять дней'), ('weekly', 'еженедельно')], default='every_day', max_length=20)),
                ('time_long', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('action_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.action')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
