# Generated by Django 5.1.4 on 2024-12-18 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.action', verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='action_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.place', verbose_name='Место выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='action_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_nice',
            field=models.BooleanField(default=False, verbose_name='Признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичная'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('every_hour', 'каждый час'), ('twice_day', 'дважды в день'), ('three_times_day', 'трижды в день'), ('every_day', 'каждый день'), ('every_two_days', 'каждые два дня'), ('every_three_days', 'каждые три дня'), ('every_five_days', 'каждые пять дней'), ('weekly', 'еженедельно')], default='every_day', max_length=20, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_long',
            field=models.IntegerField(default=0, verbose_name='Продолжительность выполнения (мин)'),
        ),
    ]
