# Generated by Django 5.1.4 on 2024-12-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_action_name_alter_habit_action_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Вознаграждение',
                'verbose_name_plural': 'Вознаграждения',
            },
        ),
        migrations.AddField(
            model_name='habit',
            name='myreward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.reward', verbose_name='Вознаграждение'),
        ),
    ]
